language: scala

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

sudo: false

env:
  global:
    - MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=256m"
    - secure: z+5AQ0JizGu1C84dU+ZRaeOSOPT30K9Q8VAby+UnSoLp6WBc2pmHuR7NIXvKq+umetLTZ1H0IpxseXAdwxTfhhXK3133t0xWaDx/9JqbbmOx7w2AoywL4+QzxO5d/QuGWuNwXrOMUQh0bf3UkQEBB/1WSEsbt87Z/cC9QylF4bu3qN6BOXh86pMkScRM+imvWwYX3E2GRKXnrsOhDjCozYIEoHDGxyuzF0uszc82RyW4aC3BcKQU0KBr6veHxMFCsEv0i/N1An31Lkw40J6FLlEQK6RTWFtXlLhNv7PfkuqOfFm3N69qCdsjwATaEDO+b3USs/Qe9bjL87NJ+87UeJJXmigbI0+13Au/Dv9AYwr3mnV3FMOC2Hx4+q7MBWEaBTWJK6wsboz0i6csfJMVdcJs1Pzo5RVyN3b92NlwMzGhtdW3vHYxGuwt5W13gSkwpGIcSfWe/Aqiju5AXUh1IZEaYQR0O2VPF4cSL+BrRFxl1Ovo893ReXAEYczwIFrdVCx5Y3RlemW5cTCFzi/5RRz1AmlBxhOB06y0Gu1QZmGD4sip7V9GqEg/fkuZfmtjOX1tcRWQZGTQp4OQn5QurqH5j2uZ+Q0S2kGyJbg4JQ73hDjn3RLS0zMbrS9iRGE86D8jOxvuN9U25htu69jFelLM/xD0oxvCjPMroXz2d6g=
    - secure: ieeWY45bUzeOv4zJcAdEopj7CEkTPxkKgQyPYSFUN3KQXSqT7GqMA3UxIbTw6K//BoMKegXfJionDruhaZWxJ8R6xrzq0oSVvODoTN7gkYBHqjseWBOH6Z11j66cx1ZxuPYcYkTy2TCZ7lhYfGolchhG8mSEhev09OH1BQ8xUgCFjYtXcCCOp+ESs78tTsvwJJJuJfiWqQTloeg+he8DG36nC7KO98J38RvzkjFGvLfntDV6A9sxCOLAFuYXFSlWOwy9finZbSejBaSW1iu1KcW2xrlHSaRLun30cRs7sliUmnqWk7+eNwgyAifHd2hmMMLuNVeh3hJm11/vsQqdmZMsdNdg+XMJ+aA21Hxs8oFA813T8LrjkbKUmBdGK6ARMPwSEh1Hl4/JUDLrlaY9KED4mu7CpjdKxtQL3E1z2qqQkSX8odSwB3HrViktlQtJTLkNmrNwl0UTHzTIx5qEsIgkHRSjLMSjsxoMGGbS8QEPKP2NjpY+yOq/oOKVwseyhp74I++ueQV9VGQ2CJ5o4KNV5opkStCImyd2gLgGXu08YkAQuArFvY+qMgZAodjZMJz2obMyI2qkNnq8PXd5Gxxirb5IReGHszc3tnRaSKySqRlmZ/ayt+Vleyx88urATH0La+Rfams+Tc6xitIVGQboKF8O1bmoiQhZOWjo+Ww=
    - secure: iGY4XKyqF79LqEHMoF9Uca7quyKiQkDZEijCn9KXRLLKsJv4MS1/YESW6ZjVfcq8UVJ1viroteMJtPMZeTjhqjq0/na2s6aSIDZrwcM1PhYMJzW5r8vr+jrvdBR/aaoxpzfI29rYeA2oqRwh9DDdHQommZKapK8tfHuPsjS5JxaH/n7PcET3MAumkxpx8Mjnkhcc1xTM48wVBPO4kl0A+xr90gFNsJj2+9mQ4P7ngiBsGX0tdRfIrfZS+1D92R5OAanNxqDlj+vGeXkg4DryD55G2LkAKJOs4Ga1w7ish2b4xqvZP+nmwc63fsmhyYMpcM2yLDcGlNdZdfKKqW3Ycqrlm4W15f4xJ5U8HH3fJlgtsfkkOAMVOT0fCCfpDXVxinyl3keHfsO+CEWK+GdNhvbh0l6niFUyXdIp6a+kVXsnoI4wch60jTNJOjrmE6EM3WH5QT770/9aUvIgJxGsMXBddi653y07C9QjY7CRUdHD/w6WPexkKY89i1HfcuwHaVgVvvx0nFh/Q0CFSjRrRz65dmKqJowMTBupRERnGyy3k8YKbokY3eyOLlOVTA+dNqI4DNDUbsSrhFFFe+Wum2hpZUd2jNdXqp9VU66fxQ1gI484so6Go6VGoyzJg+WjSZlRP3VQ6EMEPK0kAjHWYfQIHPG9WnVwIp5b0v07kp4=

matrix:
  include:
    - scala: '2.11.12'
      env: SCALAVER=2.11
    - scala: '2.12.6'
      env: SCALAVER=2.12

branches:
  only:
    - master
    - /^[0-9]+\.[0-9]+\.[0-9]+$/

cache:
  directories:
    - $HOME/.m2

before_install:
  - git clone -b travis `git config --get remote.origin.url` target/travis
  - chmod +x bin/changeScalaVersion.sh
  - bin/changeScalaVersion.sh $TRAVIS_SCALA_VERSION $SCALAVER

install: true

script:
  - |
    if [ "$TRAVIS_TAG" != "" ]; then
      mvn versions:set -DnewVersion=$TRAVIS_TAG
    fi
  - |
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
      mvn deploy -Dscala.artifact.version=$SCALAVER --settings target/travis/settings.xml
    fi
  - |
    if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then
      mvn test -B
    fi